Traceback (most recent call last):
  File "C:\Users\Victor\anaconda3\envs\pypo\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\Victor\anaconda3\envs\pypo\Lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Victor\anaconda3\envs\pypo\Lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Victor\anaconda3\envs\pypo\Lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Victor\anaconda3\envs\pypo\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Victor\anaconda3\envs\pypo\Lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Victor\anaconda3\envs\pypo\Lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\Victor\anaconda3\envs\pypo\Lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
u0 = np.array([0, 10])
lb = np.array([0, 0])
ub = np.array([100,100])

DOS_bound = np.array([[17.5, 21.0],
                    [80.0, 100.0]])

DOSresolution = [10, 10]
    

t = time.time()
fDIS, fDOS, message = nlp_based_approach(DOS_bound, 
                                          DOSresolution, 
                                          shower2x2, 
                                          u0, 
                                          lb,
                                          ub, 
                                          method='ipopt', 
                                          plot=True, 
                                          ad=False,
                                          warmstart=False)
    
    
elapsed = time.time() - t
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mAttributeError[0m                            Traceback (most recent call last)
Cell [1;32mIn[3], line 12[0m
[0;32m      8[0m DOSresolution [38;5;241m=[39m [[38;5;241m10[39m, [38;5;241m10[39m]
[0;32m     11[0m t [38;5;241m=[39m time[38;5;241m.[39mtime()
[1;32m---> 12[0m fDIS, fDOS, message [38;5;241m=[39m nlp_based_approach(DOS_bound, 
[0;32m     13[0m                                           DOSresolution, 
[0;32m     14[0m                                           shower2x2, 
[0;32m     15[0m                                           u0, 
[0;32m     16[0m                                           lb,
[0;32m     17[0m                                           ub, 
[0;32m     18[0m                                           method[38;5;241m=[39m[38;5;124m'[39m[38;5;124mipopt[39m[38;5;124m'[39m, 
[0;32m     19[0m                                           plot[38;5;241m=[39m[38;5;28;01mTrue[39;00m, 
[0;32m     20[0m                                           ad[38;5;241m=[39m[38;5;28;01mFalse[39;00m,
[0;32m     21[0m                                           warmstart[38;5;241m=[39m[38;5;28;01mFalse[39;00m)
[0;32m     24[0m elapsed [38;5;241m=[39m time[38;5;241m.[39mtime() [38;5;241m-[39m t

File [1;32mV:\Documents\python_operability\src\pypo.py:802[0m, in [0;36mnlp_based_approach[1;34m(model, DOS_bounds, DOS_resolution, u0, lb, ub, constr, method, plot, ad, warmstart)[0m
[0;32m    790[0m         [38;5;66;03m# constr['fun'] = jit(constr['fun'])[39;00m
[0;32m    791[0m         [38;5;66;03m# BUG: AD-based hessians are deactivated for in ipopt now [39;00m
[0;32m    792[0m         [38;5;66;03m# due to Cyipopt`s bug.[39;00m
[1;32m   (...)[0m
[0;32m    796[0m         [38;5;66;03m# constr['hess'] = jit(jacrev(jacrev(constr['fun'])))[39;00m
[0;32m    797[0m     [38;5;28;01melse[39;00m:
[0;32m    798[0m         [38;5;28;01mpass[39;00m
[1;32m--> 802[0m dimDOS [38;5;241m=[39m DOS_bounds[38;5;241m.[39mshape[[38;5;241m0[39m]
[0;32m    803[0m DOSPts [38;5;241m=[39m create_grid(DOS_bounds, DOS_resolution)
[0;32m    804[0m DOSPts [38;5;241m=[39m DOSPts[38;5;241m.[39mreshape([38;5;241m-[39m[38;5;241m1[39m, dimDOS)

[1;31mAttributeError[0m: 'list' object has no attribute 'shape'
AttributeError: 'list' object has no attribute 'shape'

