Traceback (most recent call last):
  File "C:\Users\vc00004\Anaconda3\envs\pypo-env\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\vc00004\Anaconda3\envs\pypo-env\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\vc00004\Anaconda3\envs\pypo-env\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\vc00004\Anaconda3\envs\pypo-env\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\vc00004\Anaconda3\envs\pypo-env\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\vc00004\Anaconda3\envs\pypo-env\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\vc00004\Anaconda3\envs\pypo-env\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\vc00004\Anaconda3\envs\pypo-env\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
    def process_model(u: AIS, d: EDS):

        y = f(u,d)
            
        return y
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
[1;32m~\AppData\Local\Temp\ipykernel_18856\2497047814.py[0m in [0;36m<cell line: 1>[1;34m()[0m
[1;32m----> 1[1;33m [1;32mdef[0m [0mprocess_model[0m[1;33m([0m[0mu[0m[1;33m:[0m [0mAIS[0m[1;33m,[0m [0md[0m[1;33m:[0m [0mEDS[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      2[0m [1;33m[0m[0m
[0;32m      3[0m     [0my[0m [1;33m=[0m [0mf[0m[1;33m([0m[0mu[0m[1;33m,[0m[0md[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      4[0m [1;33m[0m[0m
[0;32m      5[0m     [1;32mreturn[0m [0my[0m[1;33m[0m[1;33m[0m[0m

[1;31mNameError[0m: name 'AIS' is not defined
NameError: name 'AIS' is not defined

